version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: gamedom_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: gamedom_users
      MYSQL_USER: usuario
      MYSQL_PASSWORD: usuariopassword
    ports:
      - "3307:3306"  # o 3306:3306 si no tienes conflicto
    volumes:
      - db_data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d

  web:
    build: .                 # En lugar de image: php:8.0-apache
    container_name: gamedom_web
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
      - ./php:/var/www/html/php
      - ./css:/var/www/html/css
      - ./js:/var/www/html/js

volumes:
  db_data:
