let next = document.querySelector('.next')
let prev = document.querySelector('.prev')

next.addEventListener('click', function(){
    let items = document.querySelectorAll('.item')
    document.querySelector('.slide').appendChild(items[0])
})

prev.addEventListener('click', function(){
    let items = document.querySelectorAll('.item')
    document.querySelector('.slide').prepend(items[items.length - 1]) // here the length of items = 6
})

document.addEventListener("DOMContentLoaded", function () {
    const dropdownToggle = document.querySelector(".dropdown-toggle");
    const dropdownMenu = document.querySelector(".dropdown-menu");

    // Función para alternar la visibilidad del menú
    dropdownToggle.addEventListener("click", function (event) {
        event.stopPropagation(); // Evita que el clic se propague y cierre el menú
        dropdownMenu.classList.toggle("show");
    });

    // Cierra el menú si se hace clic fuera
    document.addEventListener("click", function (event) {
        if (!dropdownMenu.contains(event.target) && !dropdownToggle.contains(event.target)) {
            dropdownMenu.classList.remove("show");
        }
    });
});


const languages = {
    es: {
        login: "Iniciar sesión",
        idiomas: "Idiomas ▼",
        footer: "© 2025 CodeCrafters. Todos los derechos reservados. Todas las marcas registradas pertenecen a sus respectivos dueños en EE. UU. y otros países.",
        privacy: "Política de Privacidad",
        legal: "Información legal",
        cookies: "Cookies",
        about: "A cerca de CodeCrafters",
        Jugar: "Jugar",
        Hundirlaflota: "Hundir la flota",
        txthundirlaflota: "¡Zarpa hacia la estrategia definitiva! Toma el mando de tu escuadrón naval, despliega tus barcos y desafía a oponentes en duelos épicos. ¿Podrás hundir su flota antes de que ellos hundan la tuya?",
        Risk:"Risk",
        txtRisk:"¡Prepárate para una batalla legendaria! Tu misión es expandir tu imperio, conquistar territorios y enfrentarte a tus oponentes en un juego de estrategia. ¿Serás el líder que domine el mundo?",
        biblioteca: "Biblioteca",
        comunidad: "Comunidad",
        premios: "Premios",
        perfil: "Perfil",
        buscar: "Buscar", 
        categoria: "Categoría",
        filtrar: "Filtrar juegos",
        buscarjuego: "Buscar juegos...",
        btnfiltrar: "Filtrar"

    },

    en: {
        login: "Login",
        idiomas: "Languages ▼",
        footer: "© 2025 CodeCrafters. All rights reserved. All trademarks are the property of their respective owners in the US and other countries.",
        privacy: "Privacy Policy",
        legal: "Legal Information",
        cookies: "Cookies",
        about: "About CodeCrafters",
        Jugar: "Play",
        Hundirlaflota: "Sink the Fleet",
        txthundirlaflota: "Set sail for the ultimate strategy! Command your naval fleet, deploy your ships, and challenge opponents in epic duels. Can you sink their fleet before they sink yours?",
        Risk: "Risk",
        txtRisk: "Get ready for a legendary battle! Your mission is to expand your empire, conquer territories, and face off against your opponents in a strategy game. Will you be the leader to dominate the world?",
        biblioteca: "Library",
        comunidad: "Community",
        premios: "Awards",
        perfil: "Profile",
        buscar: "Search",
        categoria: "Category",
        filtrar: "Filter games",
        buscarjuego: "Search games...",
        btnfiltrar: "Filter"
    },
    fr: {
        login: "Se connecter",
        idiomas: "Langues ▼",
        footer: "© 2025 CodeCrafters. Tous droits réservés. Toutes les marques déposées sont la propriété de leurs détenteurs respectifs aux États-Unis et dans d'autres pays.",
        privacy: "Politique de confidentialité",
        legal: "Informations légales",
        cookies: "Cookies",
        about: "À propos de CodeCrafters",
        Jugar: "Jouer",
        Hundirlaflota: "Coulée de la flotte",
        txthundirlaflota: "Mettez le cap sur la stratégie ultime ! Prenez le commandement de votre escadron naval, déployez vos navires et défiez vos adversaires dans des duels épiques. Pourrez-vous couler leur flotte avant qu'ils ne coulent la vôtre ?",
        Risk: "Risk",
        txtRisk: "Préparez-vous pour une bataille légendaire ! Votre mission est d'étendre votre empire, de conquérir des territoires et d'affronter vos adversaires dans un jeu de stratégie. Serez-vous le leader qui dominera le monde ?",
        biblioteca: "Bibliothèque",
        comunidad: "Communauté",
        premios: "Récompenses",
        perfil: "Profil",
        buscar: "Rechercher",
        categoria: "Catégorie",
        filtrar: "Filtrer les jeux",
        buscarjuego: "Rechercher des jeux...",
        btnfiltrar: "Filtrer"
    },
    de: {
        login: "Anmelden",
        idiomas: "Sprachen ▼",
        footer: "© 2025 CodeCrafters. Alle Rechte vorbehalten.",
        privacy: "Datenschutzrichtlinie",
        legal: "Rechtliche Informationen",
        cookies: "Cookies",
        about: "Über CodeCrafters",
        Jugar: "Spielen",
        Hundirlaflota: "Flotte versenken",
        txthundirlaflota: "Setze die Segel für die ultimative Strategie! Kommandiere deine Flotte, setze deine Schiffe ein und fordere Gegner zu epischen Duellen heraus. Kannst du ihre Flotte versenken, bevor sie deine versenken?",
        Risk: "Risk",
        txtRisk: "Bereite dich auf eine legendäre Schlacht vor! Deine Mission ist es, dein Imperium auszubauen, Gebiete zu erobern und dich in einem Strategie-Spiel mit deinen Gegnern zu messen. Wirst du der Führer sein, der die Welt beherrscht?",
        biblioteca: "Bibliothek",
        comunidad: "Gemeinschaft",
        premios: "Preise",
        perfil: "Profil",
        buscar: "Suchen",
        categoria: "Kategorie",
        filtrar: "Spiele filtern",
        buscarjuego: "Spiele suchen...",
        btnfiltrar: "Filtern"
    },
    it: {
        login: "Accedi",
        idiomas: "Lingue ▼",
        footer: "© 2025 CodeCrafters. Tutti i diritti riservati.",
        privacy: "Informativa sulla privacy",
        legal: "Informazioni legali",
        cookies: "Cookie",
        about: "Informazioni su CodeCrafters",
        Jugar: "Giocare",
        Hundirlaflota: "Affondare la flotta",
        txthundirlaflota: "Set sail per la strategia definitiva! Comanda la tua flotta navale, dispiega le tue navi e sfida gli avversari in duelli epici. Riuscirai ad affondare la loro flotta prima che affondino la tua?",
        Risk: "Risk",
        txtRisk: "Preparati per una battaglia leggendaria! La tua missione è espandere il tuo impero, conquistare territori e affrontare i tuoi avversari in un gioco di strategia. Sarai tu il leader che dominerà il mondo?",
        biblioteca: "Biblioteca",
        comunidad: "Comunità",
        premios: "Premi",
        perfil: "Profilo",
        buscar: "Cerca",
        categoria: "Categoria",
        filtrar: "Filtra giochi",
        buscarjuego: "Cerca giochi...",
        btnfiltrar: "Filtra"
    },
    pt: {
        login: "Entrar",  
        idiomas: "Idiomas ▼",  
        footer: "© 2025 CodeCrafters. Todos os direitos reservados.",  
        privacy: "Política de Privacidade",  
        legal: "Informações Legais",  
        cookies: "Cookies",  
        about: "Sobre CodeCrafters",  
        Jugar: "Jogar",  
        Hundirlaflota: "Afundar a Frota",  
        txthundirlaflota: "Levante âncora para a estratégia suprema! Comande sua frota naval, posicione seus navios e desafie adversários em duelos épicos. Você conseguirá afundar a frota deles antes que afundem a sua?",  
        Risk: "Risk",  
        txtRisk: "Prepare-se para uma batalha lendária! Sua missão é expandir seu império, conquistar territórios e enfrentar adversários em um jogo de estratégia. Será você o líder que dominará o mundo?",  
        biblioteca: "Biblioteca",  
        comunidad: "Comunidade",  
        premios: "Prêmios",  
        perfil: "Perfil",  
        buscar: "Pesquisar",  
        categoria: "Categoria",  
        filtrar: "Filtrar jogos",  
        buscarjuego: "Pesquisar jogos...",  
        btnfiltrar: "Filtrar"  
        
    },
    ru: {
        login: "Войти",  
        idiomas: "Языки ▼",  
        footer: "© 2025 CodeCrafters. Все права защищены.",  
        privacy: "Политика конфиденциальности",  
        legal: "Правовая информация",  
        cookies: "Файлы cookie",  
        about: "О CodeCrafters",  
        Jugar: "Играть",  
        Hundirlaflota: "Потопить флот",  
        txthundirlaflota: "Поднимите паруса для главной стратегии! Управляйте своим флотом, размещайте корабли и сражайтесь с противниками в эпических дуэлях. Сможете ли вы потопить их флот раньше, чем они потопят ваш?",  
        Risk: "Риск",  
        txtRisk: "Готовьтесь к легендарной битве! Ваша миссия – расширить империю, захватить территории и сразиться с противниками в стратегической игре. Станете ли вы лидером, который завоюет весь мир?",  
        biblioteca: "Библиотека",  
        comunidad: "Сообщество",  
        premios: "Награды",  
        perfil: "Профиль",  
        buscar: "Поиск",  
        categoria: "Категория",  
        filtrar: "Фильтровать игры",  
        buscarjuego: "Искать игры...",  
        btnfiltrar: "Фильтровать"  

    },
    cn: {
        login: "登录",  
        idiomas: "语言 ▼",  
        footer: "© 2025 CodeCrafters. 保留所有权利。",  
        privacy: "隐私政策",  
        legal: "法律信息",  
        cookies: "Cookie",  
        about: "关于 CodeCrafters",  
        Jugar: "玩游戏",  
        Hundirlaflota: "击沉舰队",  
        txthundirlaflota: "扬帆起航，制定终极策略！指挥您的舰队，部署战舰，与对手展开史诗对决。您能否在他们击沉您的舰队之前先击沉他们的舰队？",  
        Risk: "风险",  
        txtRisk: "准备好迎接一场传奇战役吧！您的任务是扩展帝国，占领领土，并在策略游戏中挑战对手。您会成为统治世界的领袖吗？",  
        biblioteca: "图书馆",  
        comunidad: "社区",  
        premios: "奖项",  
        perfil: "个人资料",  
        buscar: "搜索",  
        categoria: "类别",  
        filtrar: "筛选游戏",  
        buscarjuego: "搜索游戏...",  
        btnfiltrar: "筛选"          
    },
    jp: {
        login: "ログイン",  
        idiomas: "言語 ▼",  
        footer: "© 2025 CodeCrafters. 全著作権所有。",  
        privacy: "プライバシーポリシー",  
        legal: "法的情報",  
        cookies: "クッキー",  
        about: "CodeCraftersについて",  
        Jugar: "プレイ",  
        Hundirlaflota: "艦隊を沈めろ",  
        txthundirlaflota: "究極の戦略を掲げて出航せよ！ 艦隊を指揮し、戦艦を配置して、対戦相手と壮大な戦いを繰り広げましょう。あなたは彼らの艦隊を沈める前に、先に沈めることができるでしょうか？",  
        Risk: "リスク",  
        txtRisk: "伝説的な戦いの準備をしよう！ あなたの使命は、帝国を拡張し、領土を征服し、戦略ゲームで対戦相手に挑むことです。世界を支配するリーダーになれるでしょうか？",  
        biblioteca: "ライブラリ",  
        comunidad: "コミュニティ",  
        premios: "賞",  
        perfil: "プロフィール",  
        buscar: "検索",  
        categoria: "カテゴリー",  
        filtrar: "ゲームをフィルター",  
        buscarjuego: "ゲームを検索...",  
        btnfiltrar: "フィルター"  

    },
    kr: {
        login: "로그인",  
        idiomas: "언어 ▼",  
        footer: "© 2025 CodeCrafters. 모든 권리 보유.",  
        privacy: "개인정보 보호정책",  
        legal: "법적 정보",  
        cookies: "쿠키",  
        about: "CodeCrafters 소개",  
        Jugar: "게임하기",  
        Hundirlaflota: "함대를 침몰시켜라",  
        txthundirlaflota: "궁극의 전략으로 출항하세요! 당신의 함대를 지휘하고 전함을 배치하며 상대방과 장대한 전투를 벌이세요. 상대 함대를 먼저 침몰시키는 것은 과연 누구일까요?",  
        Risk: "리스크",  
        txtRisk: "전설적인 전투를 준비하세요! 당신의 임무는 제국을 확장하고 영토를 정복하며 전략 게임에서 상대를 물리치는 것입니다. 세계를 지배하는 리더가 될 수 있을까요?",  
        biblioteca: "라이브러리",  
        comunidad: "커뮤니티",  
        premios: "보상",  
        perfil: "프로필",  
        buscar: "검색",  
        categoria: "카테고리",  
        filtrar: "게임 필터링",  
        buscarjuego: "게임 검색...",  
        btnfiltrar: "필터"  
    },
    sa: {
        login: "تسجيل الدخول",  
        idiomas: "اللغات ▼",  
        footer: "© 2025 CodeCrafters. جميع الحقوق محفوظة.",  
        privacy: "سياسة الخصوصية",  
        legal: "المعلومات القانونية",  
        cookies: "الكوكيز",  
        about: "حول CodeCrafters",  
        Jugar: "اللعب",  
        Hundirlaflota: "إغراق الأسطول",  
        txthundirlaflota: "أبحر لتحقيق الاستراتيجية المثالية! قُد أسطولك، ووزّع سفنك، وتحدى خصومك في معارك ملحمية. هل ستتمكن من إغراق أسطولهم قبل أن يغرقوا أسطولك؟",  
        Risk: "ريسك",  
        txtRisk: "استعد لمعركة أسطورية! مهمتك هي توسيع إمبراطوريتك، والسيطرة على الأراضي، ومواجهة خصومك في لعبة استراتيجية. هل ستكون القائد الذي يسيطر على العالم؟",  
        biblioteca: "المكتبة",  
        comunidad: "المجتمع",  
        premios: "الجوائز",  
        perfil: "الملف الشخصي",  
        buscar: "بحث",  
        categoria: "الفئة",  
        filtrar: "تصفية الألعاب",  
        buscarjuego: "بحث عن ألعاب...",  
        btnfiltrar: "تصفية"  

    },
    in: {
        login: "लॉगिन",  
        idiomas: "भाषाएँ ▼",  
        footer: "© 2025 CodeCrafters. सर्वाधिकार सुरक्षित।",  
        privacy: "गोपनीयता नीति",  
        legal: "कानूनी जानकारी",  
        cookies: "कुकीज़",  
        about: "CodeCrafters के बारे में",  
        Jugar: "खेलें",  
        Hundirlaflota: "बेड़े को डुबोएँ",  
        txthundirlaflota: "सर्वश्रेष्ठ रणनीति के लिए तैयार हो जाइए! अपने बेड़े की कमान संभालें, अपने जहाजों को तैनात करें, और महाकाव्य मुकाबलों में अपने विरोधियों को चुनौती दें। क्या आप उनके बेड़े को डुबोने से पहले अपना बचा पाएंगे?",  
        Risk: "रिस्क",  
        txtRisk: "एक ऐतिहासिक लड़ाई के लिए तैयार हो जाइए! आपकी चुनौती है अपने साम्राज्य का विस्तार करना, क्षेत्रों पर कब्जा करना और रणनीतिक खेल में अपने विरोधियों से मुकाबला करना। क्या आप वह नेता होंगे जो दुनिया पर राज करेगा?",  
        biblioteca: "पुस्तकालय",  
        comunidad: "समुदाय",  
        premios: "पुरस्कार",  
        perfil: "प्रोफ़ाइल",  
        buscar: "खोजें",  
        categoria: "श्रेणी",  
        filtrar: "खेल फ़िल्टर करें",  
        buscarjuego: "खेल खोजें...",  
        btnfiltrar: "फ़िल्टर करें"  
    },
    tr: {
        login: "Giriş Yap",  
        idiomas: "Diller ▼",  
        footer: "© 2025 CodeCrafters. Tüm hakları saklıdır.",  
        privacy: "Gizlilik Politikası",  
        legal: "Yasal Bilgiler",  
        cookies: "Çerezler",  
        about: "CodeCrafters Hakkında",  
        Jugar: "Oyna",  
        Hundirlaflota: "Filo Batır",  
        txthundirlaflota: "Nihai strateji için yelken açın! Filonuzu yönetin, gemilerinizi konuşlandırın ve destansı düellolarda rakiplerinize meydan okuyun. Onların filosunu batırmadan önce sizinki hayatta kalabilecek mi?",  
        Risk: "Risk",  
        txtRisk: "Efsanevi bir savaşa hazır olun! Göreviniz imparatorluğunuzu genişletmek, toprakları fethetmek ve strateji oyununda rakiplerinizle yüzleşmek. Dünyaya hükmedecek lider siz olacak mısınız?",  
        biblioteca: "Kütüphane",  
        comunidad: "Topluluk",  
        premios: "Ödüller",  
        perfil: "Profil",  
        buscar: "Ara",  
        categoria: "Kategori",  
        filtrar: "Oyunları Filtrele",  
        buscarjuego: "Oyun Ara...",  
        btnfiltrar: "Filtrele"  
},
    nl: {
        login: "Inloggen",  
        idiomas: "Talen ▼",  
        footer: "© 2025 CodeCrafters. Alle rechten voorbehouden.",  
        privacy: "Privacybeleid",  
        legal: "Juridische Informatie",  
        cookies: "Cookies",  
        about: "Over CodeCrafters",  
        Jugar: "Spelen",  
        Hundirlaflota: "Vloot Zinken",  
        txthundirlaflota: "Zet koers voor de ultieme strategie! Beheer je vloot, zet je schepen in en daag je tegenstanders uit in epische duels. Kun jij hun vloot zinken voordat zij de jouwe vernietigen?",  
        Risk: "Risk",  
        txtRisk: "Bereid je voor op een legendarische strijd! Jouw missie is om je rijk uit te breiden, gebieden te veroveren en het tegen je tegenstanders op te nemen in een strategiespel. Ben jij de leider die de wereld zal domineren?",  
        biblioteca: "Bibliotheek",  
        comunidad: "Gemeenschap",  
        premios: "Prijzen",  
        perfil: "Profiel",  
        buscar: "Zoeken",  
        categoria: "Categorie",  
        filtrar: "Filter Spellen",  
        buscarjuego: "Zoek spellen...",  
        btnfiltrar: "Filteren"  
    },
    se: {
        login: "Logga in",  
        idiomas: "Språk ▼",  
        footer: "© 2025 CodeCrafters. Alla rättigheter förbehållna.",  
        privacy: "Integritetspolicy",  
        legal: "Juridisk information",  
        cookies: "Cookies",  
        about: "Om CodeCrafters",  
        Jugar: "Spela",  
        Hundirlaflota: "Sänk flottan",  
        txthundirlaflota: "Ge dig ut på jakt för den ultimata strategin! Led din flotta, placera dina fartyg och utmana dina motståndare i episka dueller. Kan du sänka deras flotta innan de sänker din?",  
        Risk: "Risk",  
        txtRisk: "Förbered dig på ett legendariskt slag! Ditt uppdrag är att utvidga ditt imperium, erövra territorier och möta dina motståndare i ett strategispel. Kommer du att vara den ledare som kommer att dominera världen?",  
        biblioteca: "Bibliotek",  
        comunidad: "Gemenskap",  
        premios: "Priser",  
        perfil: "Profil",  
        buscar: "Sök",  
        categoria: "Kategori",  
        filtrar: "Filtrera spel",  
        buscarjuego: "Sök spel...",  
        btnfiltrar: "Filtrera"  
    },
    pl: {
        login: "Zaloguj się",  
        idiomas: "Języki ▼",  
        footer: "© 2025 CodeCrafters. Wszelkie prawa zastrzeżone.",  
        privacy: "Polityka prywatności",  
        legal: "Informacje prawne",  
        cookies: "Pliki cookie",  
        about: "O CodeCrafters",  
        Jugar: "Graj",  
        Hundirlaflota: "Zatop flotę",  
        txthundirlaflota: "Wypłyń na morze, by stworzyć najlepszą strategię! Dowódź swoją flotą, rozmieszczaj statki i wyzywaj przeciwników na epickie pojedynki. Czy zdołasz zatopić ich flotę, zanim oni zatopią twoją?",  
        Risk: "Risk",  
        txtRisk: "Przygotuj się na legendarną bitwę! Twoja misja to rozszerzanie swojego imperium, podbijanie terytoriów i rywalizowanie z przeciwnikami w grze strategicznej. Czy będziesz liderem, który zdominuje świat?",  
        biblioteca: "Biblioteka",  
        comunidad: "Społeczność",  
        premios: "Nagrody",  
        perfil: "Profil",  
        buscar: "Szukaj",  
        categoria: "Kategoria",  
        filtrar: "Filtruj gry",  
        buscarjuego: "Szukaj gier...",  
        btnfiltrar: "Filtruj"  
    },
    gr: { 
        login: "Σύνδεση",  
        idiomas: "Γλώσσες ▼",  
        footer: "© 2025 CodeCrafters. Όλα τα δικαιώματα διατηρούνται.",  
        privacy: "Πολιτική απορρήτου",  
        legal: "Νομικές πληροφορίες",  
        cookies: "Cookies",  
        about: "Σχετικά με το CodeCrafters",  
        Jugar: "Παίξε",  
        Hundirlaflota: "Βύθισε τον στόλο",  
        txthundirlaflota: "Αναχώρησε για την απόλυτη στρατηγική! Διοίκησε τον στόλο σου, τοποθέτησε τα πλοία σου και πρόκλησε αντιπάλους σε επικές αναμετρήσεις. Θα καταφέρεις να βυθίσεις τον στόλο τους πριν εκείνοι βυθίσουν τον δικό σου;",  
        Risk: "Risk",  
        txtRisk: "Ετοιμάσου για μια θρυλική μάχη! Αποστολή σου είναι να επεκτείνεις την αυτοκρατορία σου, να καταλάβεις εδάφη και να αντιμετωπίσεις τους αντιπάλους σου σε ένα παιχνίδι στρατηγικής. Θα είσαι ο ηγέτης που θα κυριαρχήσει στον κόσμο;",  
        biblioteca: "Βιβλιοθήκη",  
        comunidad: "Κοινότητα",  
        premios: "Βραβεία",  
        perfil: "Προφίλ",  
        buscar: "Αναζήτηση",  
        categoria: "Κατηγορία",  
        filtrar: "Φιλτράρετε τα παιχνίδια",  
        buscarjuego: "Αναζήτηση παιχνιδιών...",  
        btnfiltrar: "Φιλτράρετε"  
 },
    il: { 
        login: "התחברות",  
        idiomas: "שפות ▼",  
        footer: "© 2025 CodeCrafters. כל הזכויות שמורות.",  
        privacy: "מדיניות פרטיות",  
        legal: "מידע משפטי",  
        cookies: "עוגיות",  
        about: "על CodeCrafters",  
        Jugar: "שחק",  
        Hundirlaflota: "טביעת הצי",  
        txthundirlaflota: "הפליגו לאסטרטגיה האולטימטיבית! פיקחו על הצי שלכם, הציבו את הספינות וקדו את היריבים לקרב אפי. האם תצליחו לטבוע את הצי שלהם לפני שהם טובעים את שלכם?",  
        Risk: "Risk",  
        txtRisk: "הכינו את עצמכם לקרב אגדי! המשימה שלכם היא להרחיב את האימפריה שלכם, להכבוש טריטוריות ולהתמודד עם היריבים שלכם במשחק אסטרטגיה. האם אתם תהיו המנהיגים שישלטו בעולם?",  
        biblioteca: "ספרייה",  
        comunidad: "קהילה",  
        premios: "פרסים",  
        perfil: "פרופיל",  
        buscar: "חפש",  
        categoria: "קטגוריה",  
        filtrar: "סנן משחקים",  
        buscarjuego: "חפש משחקים...",  
        btnfiltrar: "סנן"  
 },
    fi: { 
        login: "Kirjaudu sisään",  
        idiomas: "Kielet ▼",  
        footer: "© 2025 CodeCrafters. Kaikki oikeudet pidätetään.",  
        privacy: "Tietosuojakäytäntö",  
        legal: "Lakimies",  
        cookies: "Evästeet",  
        about: "Tietoja CodeCraftersista",  
        Jugar: "Pelaa",  
        Hundirlaflota: "Upota laivasto",  
        txthundirlaflota: "Aloita matka kohti täydellistä strategiaa! Johda omaa laivastoa, sijoita aluksesi ja haasta vastustajat eeppisiin taisteluihin. Pystytkö upottamaan heidän laivastonsa ennen kuin he upottavat sinun?",  
        Risk: "Risk",  
        txtRisk: "Valmistaudu legendaariseen taisteluun! Tehtäväsi on laajentaa valtakuntaasi, valloittaa alueita ja kohdata vastustajasi strategiassa. Oletko sinä se johtaja, joka hallitsee maailmaa?",  
        biblioteca: "Kirjasto",  
        comunidad: "Yhteisö",  
        premios: "Palkinnot",  
        perfil: "Profiili",  
        buscar: "Etsi",  
        categoria: "Kategoria",  
        filtrar: "Suodata pelejä",  
        buscarjuego: "Etsi pelejä...",  
        btnfiltrar: "Suodata"  
    },
    dk: { 
        login: "Log ind",  
        idiomas: "Sprog ▼",  
        footer: "© 2025 CodeCrafters. Alle rettigheder forbeholdes.",  
        privacy: "Privatlivspolitik",  
        legal: "Juridisk",  
        cookies: "Cookies",  
        about: "Om CodeCrafters",  
        Jugar: "Spil",  
        Hundirlaflota: "Sænk flåden",  
        txthundirlaflota: "Sæt sejl mod den ultimative strategi! Led din flåde, placer dine skibe og udfordr modstandere i episke dueller. Kan du sænke deres flåde, før de sænker din?",  
        Risk: "Risk",  
        txtRisk: "Gør dig klar til en legendarisk kamp! Din mission er at udvide dit imperium, erobre territorier og bekæmpe dine modstandere i et strategispil. Vil du være lederen, der dominerer verden?",  
        biblioteca: "Bibliotek",  
        comunidad: "Fællesskab",  
        premios: "Præmier",  
        perfil: "Profil",  
        buscar: "Søg",  
        categoria: "Kategori",  
        filtrar: "Filtrer spil",  
        buscarjuego: "Søg efter spil...",  
        btnfiltrar: "Filtrer"  
    },
    hu: { 
        login: "Bejelentkezés",  
        idiomas: "Nyelvek ▼",  
        footer: "© 2025 CodeCrafters. Minden jog fenntartva.",  
        privacy: "Adatvédelmi irányelvek",  
        legal: "Jogi információk",  
        cookies: "Cookie-k",  
        about: "A CodeCrafters-ról",  
        Jugar: "Játszani",  
        Hundirlaflota: "Süllyeszd el a flottát",  
        txthundirlaflota: "Vitorlázz a végső stratégia felé! Vezesd a flottádat, helyezd el hajóidat, és kihívásokat állítsd az ellenfeleid elé epikus párbajokban. El fogod süllyeszteni a flottájukat, mielőtt ők süllyesztenek el téged?",  
        Risk: "Risk",  
        txtRisk: "Készülj fel egy legendás csatára! Küldetésed, hogy bővítsd birodalmadat, hódíts el területeket és harcolj ellenfeleiddel egy stratégiai játékban. Te leszel az a vezető, aki uralja a világot?",  
        biblioteca: "Könyvtár",  
        comunidad: "Közösség",  
        premios: "Díjak",  
        perfil: "Profil",  
        buscar: "Keresés",  
        categoria: "Kategória",  
        filtrar: "Szűrd a játékokat",  
        buscarjuego: "Játék keresése...",  
        btnfiltrar: "Szűrés"  
    },
    cz: { 
        login: "Přihlásit se",  
        idiomas: "Jazyky ▼",  
        footer: "© 2025 CodeCrafters. Všechna práva vyhrazena.",  
        privacy: "Zásady ochrany osobních údajů",  
        legal: "Právní informace",  
        cookies: "Cookies",  
        about: "O CodeCrafters",  
        Jugar: "Hrát",  
        Hundirlaflota: "Sundejte flotilu",  
        txthundirlaflota: "Vyplujte na cestu za ultimátní strategií! Vedejte svou flotilu, umístěte své lodě a vyzvěte soupeře k epickým soubojům. Podaří se vám potopit jejich flotilu dříve, než oni potopí tu vaši?",  
        Risk: "Risk",  
        txtRisk: "Připravte se na legendární bitvu! Vaším úkolem je rozšířit své impérium, dobyvat území a čelit soupeřům v strategické hře. Budete tím lídrem, který bude vládnout světu?",  
        biblioteca: "Knihovna",  
        comunidad: "Komunita",  
        premios: "Ceny",  
        perfil: "Profil",  
        buscar: "Hledat",  
        categoria: "Kategorie",  
        filtrar: "Filtruj hry",  
        buscarjuego: "Hledat hry...",  
        btnfiltrar: "Filtruj"  
},
    ro: { 
        login: "Autentificare",  
        idiomas: "Limbi ▼",  
        footer: "© 2025 CodeCrafters. Toate drepturile rezervate.",  
        privacy: "Politica de confidențialitate",  
        legal: "Informații legale",  
        cookies: "Cookie-uri",  
        about: "Despre CodeCrafters",  
        Jugar: "Joacă",  
        Hundirlaflota: "Scufunda flota",  
        txthundirlaflota: "Porniți în călătoria supremă a strategiei! Comandați-vă flota, plasați-vă navele și provocați-vă adversarii în dueluri epice. Reușiți să scufundați flota lor înainte să o scufundeți pe a voastră?",  
        Risk: "Risk",  
        txtRisk: "Pregătește-te pentru o bătălie legendară! Misiunea ta este să îți extinzi imperiul, să cucerești teritorii și să înfrunți adversarii într-un joc de strategie. Vei fi liderul care va domina lumea?",  
        biblioteca: "Bibliotecă",  
        comunidad: "Comunitate",  
        premios: "Premii",  
        perfil: "Profil",  
        buscar: "Căutare",  
        categoria: "Categorie",  
        filtrar: "Filtrează jocuri",  
        buscarjuego: "Căutare jocuri...",  
        btnfiltrar: "Filtrează"  
    },
    bg: { 
        login: "Вход",  
        idiomas: "Езици ▼",  
        footer: "© 2025 CodeCrafters. Всички права запазени.",  
        privacy: "Политика за поверителност",  
        legal: "Правна информация",  
        cookies: "Бисквитки",  
        about: "За CodeCrafters",  
        Jugar: "Играй",  
        Hundirlaflota: "Потопи флота",  
        txthundirlaflota: "Започнете пътешествието към крайната стратегия! Ръководете флота си, разположете корабите си и се предизвикайте в епични дуели. Ще успеете ли да потопите техния флот преди да потопят вашия?",  
        Risk: "Риск",  
        txtRisk: "Подгответе се за легендарна битка! Вашата мисия е да разширите империята си, да завоювате територии и да се изправите срещу своите противници в игра на стратегия. Ще бъдете ли лидерът, който ще доминира в света?",  
        biblioteca: "Библиотека",  
        comunidad: "Общност",  
        premios: "Награди",  
        perfil: "Профил",  
        buscar: "Търсене",  
        categoria: "Категория",  
        filtrar: "Филтрирай игри",  
        buscarjuego: "Търсене на игри...",  
        btnfiltrar: "Филтрирай"  
 
    },
    ua: { 
        login: "Увійти",  
        idiomas: "Мови ▼",  
        footer: "© 2025 CodeCrafters. Всі права захищені.",  
        privacy: "Політика конфіденційності",  
        legal: "Юридична інформація",  
        cookies: "Файли cookie",  
        about: "Про CodeCrafters",  
        Jugar: "Грати",  
        Hundirlaflota: "Занурити флот",  
        txthundirlaflota: "Відправляйтеся в подорож до остаточної стратегії! Керуйте своїм флотом, розміщуйте свої кораблі та змагайтеся з суперниками в епічних дуелях. Чи зможете ви потопити їхній флот до того, як вони потоплять ваш?",  
        Risk: "Ризик",  
        txtRisk: "Готуйтеся до легендарної битви! Ваше завдання — розширити свою імперію, захоплювати території та боротися з суперниками в стратегічній грі. Чи будете ви лідером, який домінуватиме в світі?",  
        biblioteca: "Бібліотека",  
        comunidad: "Спільнота",  
        premios: "Нагороди",  
        perfil: "Профіль",  
        buscar: "Пошук",  
        categoria: "Категорія",  
        filtrar: "Фільтрувати іг"

    },
    th: { 
        login: "เข้าสู่ระบบ",  
        idiomas: "ภาษา ▼",  
        footer: "© 2025 CodeCrafters. สงวนลิขสิทธิ์.",  
        privacy: "นโยบายความเป็นส่วนตัว",  
        legal: "ข้อมูลทางกฎหมาย",  
        cookies: "คุกกี้",  
        about: "เกี่ยวกับ CodeCrafters",  
        Jugar: "เล่น",  
        Hundirlaflota: "จมกองเรือ",  
        txthundirlaflota: "ออกเดินทางสู่กลยุทธ์สุดท้าย! ควบคุมกองเรือของคุณ วางเรือของคุณและท้าทายคู่แข่งในศึกดวลอันยิ่งใหญ่ คุณจะสามารถจมกองเรือของพวกเขาก่อนที่พวกเขาจะจมกองเรือของคุณได้หรือไม่?",  
        Risk: "ความเสี่ยง",  
        txtRisk: "เตรียมตัวสำหรับการต่อสู้ระดับตำนาน! ภารกิจของคุณคือขยายอาณาจักรของคุณ ยึดครองดินแดนและต่อสู้กับคู่แข่งในเกมกลยุทธ์ คุณจะเป็นผู้นำที่ครองโลกได้หรือไม่?",  
        biblioteca: "ห้องสมุด",  
        comunidad: "ชุมชน",  
        premios: "รางวัล",  
        perfil: "โปรไฟล์",  
        buscar: "ค้นหา",  
        categoria: "หมวดหมู่",  
        filtrar: "กรองเกม",  
        buscarjuego: "ค้นหาเกม...",  
        btnfiltrar: "กรอง"  
 },
    id: { 
        login: "Masuk",  
        idiomas: "Bahasa ▼",  
        footer: "© 2025 CodeCrafters. Semua hak dilindungi undang-undang.",  
        privacy: "Kebijakan Privasi",  
        legal: "Informasi Hukum",  
        cookies: "Cookie",  
        about: "Tentang CodeCrafters",  
        Jugar: "Mainkan",  
        Hundirlaflota: "Tenggelamkan Armada",  
        txthundirlaflota: "Berlayar menuju strategi terakhir! Perintahkan armada Anda, atur kapal Anda, dan tantang lawan dalam duel epik. Bisakah Anda menenggelamkan armada mereka sebelum mereka menenggelamkan Anda?",  
        Risk: "Risk",  
        txtRisk: "Bersiaplah untuk pertempuran legendaris! Misi Anda adalah memperluas kerajaan Anda, menaklukkan wilayah, dan bertarung melawan lawan dalam permainan strategi. Akankah Anda menjadi pemimpin yang menguasai dunia?",  
        biblioteca: "Perpustakaan",  
        comunidad: "Komunitas",  
        premios: "Hadiah",  
        perfil: "Profil",  
        buscar: "Cari",  
        categoria: "Kategori",  
        filtrar: "Saring permainan",  
        buscarjuego: "Cari permainan...",  
        btnfiltrar: "Saring"  
        
    },
    vn: { 
        login: "Đăng nhập",  
        idiomas: "Ngôn ngữ ▼",  
        footer: "© 2025 CodeCrafters. Bảo lưu mọi quyền.",  
        privacy: "Chính sách bảo mật",  
        legal: "Thông tin pháp lý",  
        cookies: "Cookie",  
        about: "Giới thiệu về CodeCrafters",  
        Jugar: "Chơi",  
        Hundirlaflota: "Đánh chìm hạm đội",  
        txthundirlaflota: "Khởi hành cho chiến lược cuối cùng! Hãy chỉ huy hạm đội của bạn, bố trí tàu chiến và thách thức đối thủ trong những cuộc đấu tay đôi sử thi. Liệu bạn có thể đánh chìm hạm đội của họ trước khi họ đánh chìm của bạn?",  
        Risk: "Risk",  
        txtRisk: "Chuẩn bị cho một trận chiến huyền thoại! Nhiệm vụ của bạn là mở rộng đế chế, chinh phục lãnh thổ và chiến đấu với đối thủ trong một trò chơi chiến lược. Liệu bạn có trở thành người lãnh đạo thống trị thế giới?",  
        biblioteca: "Thư viện",  
        comunidad: "Cộng đồng",  
        premios: "Giải thưởng",  
        perfil: "Hồ sơ",  
        buscar: "Tìm kiếm",  
        categoria: "Danh mục",  
        filtrar: "Lọc trò chơi",  
        buscarjuego: "Tìm trò chơi...",  
        btnfiltrar: "Lọc"  
 },
    ir: { 
        login: "ورود",  
        idiomas: "زبان‌ها ▼",  
        footer: "© 2025 CodeCrafters. کلیه حقوق محفوظ است.",  
        privacy: "سیاست حفظ حریم خصوصی",  
        legal: "اطلاعات قانونی",  
        cookies: "کوکی‌ها",  
        about: "درباره CodeCrafters",  
        Jugar: "بازی کردن",  
        Hundirlaflota: "غرق کردن ناوگان",  
        txthundirlaflota: "برای استراتژی نهایی آماده شوید! فرماندهی ناوگان خود را به عهده بگیرید، کشتی‌های خود را مستقر کنید و با حریفان خود در نبردهای حماسی مبارزه کنید. آیا می‌توانید ناوگان آنها را قبل از اینکه آنها ناوگان شما را غرق کنند، نابود کنید؟",  
        Risk: "ریسک",  
        txtRisk: "برای یک نبرد حماسی آماده شوید! ماموریت شما گسترش امپراتوری خود، فتح سرزمین‌ها و مقابله با حریفان در یک بازی استراتژیک است. آیا شما رهبر جهانی خواهید شد؟",  
        biblioteca: "کتابخانه",  
        comunidad: "جامعه",  
        premios: "جوایز",  
        perfil: "پروفایل",  
        buscar: "جستجو",  
        categoria: "دسته‌بندی",  
        filtrar: "فیلتر بازی‌ها",  
        buscarjuego: "جستجوی بازی‌ها...",  
        btnfiltrar: "فیلتر"          
    }

};

function changeLanguage(lang) {
    // Cambiar el idioma
    if (languages[lang]) {
        localStorage.setItem('language', lang); // Guardar el idioma en localStorage
        
        const elements = document.querySelectorAll('[data-text]');
        elements.forEach(function (element) {
            const textKey = element.getAttribute('data-text');
            if (languages[lang][textKey]) {
                element.innerHTML = languages[lang][textKey];
            }
        });
    }
}

// Al cargar la página, verificar si hay un idioma guardado
window.onload = function () {
    const savedLang = localStorage.getItem('language') || 'es'; // 'es' es el idioma por defecto
    changeLanguage(savedLang);
};



